GitHub:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

🌐 Translations:
- changed-files:
  - any-glob-to-any-file: 'i18n/**/*'
  - any-glob-to-any-file: 'app/i18n.py'

🧪 Tests:
- changed-files:
  - any-glob-to-any-file: 'tests/**/*'

🐳 Docker:
- changed-files:
  - any-glob-to-any-file: 'docker/**/*'
  - any-glob-to-any-file: 'Dockerfile'
  - any-glob-to-any-file: 'docker-compose.yml'

API:
- changed-files:
  - any-glob-to-any-file: 'app/knowledge_panels.py'
  - any-glob-to-any-file: 'app/main.py'
  - any-glob-to-any-file: 'app/off.py'
  - any-glob-to-any-file: 'app/wikidata_utils.py'
  - any-glob-to-any-file: 'app/settings.py'

Models:
- changed-files:
  - any-glob-to-any-file: 'app/models.py'

📚 Documentation:
  - any-glob-to-any-file: ['*.MD']
